config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :order_sheets
  resources :quarterbreeds
    get "quarterbreed/information" => "quarterbreeds#information", as: :quarterbreed_information

  resources :tr7s
  resources :mark_quarterbreeds
  resources :xj6_quarterbreeds
  resources :etype_v12s

  resources :datsun_zcars
    get "datsun_zcar/information" => "datsun_zcars#information", as: :datsun_zcar_information

  get 'jaguars' =>'pages#jaguars', as: :jaguars
  get 'xj-sedans' => 'jaguars#xj_sedans', as: :xj_sedans
  get 'triumph-tr7' => 'pages#triumph_tr7', as: :triumph_tr7
  get 'chevy-v8' => 'pages#chevy_v8', as: :chevy_v8

  get 'order_forms' => 'pages#order_forms', as: :order_forms
  get 'home2' => 'pages#home2', as: :home2
  get 'print-etype-v12/:id' => 'etype_v12s#print_etype_v12_pdf', as: :print_etype_v12_pdf
  get 'print-xj6-quarterbreeds-pdf/:id' => 'xj6_quarterbreeds#print_xj6_pdf', as: :print_xj6_pdf
  get 'print-mark-quarterbreeds-pdf/:id' => 'mark_quarterbreeds#print_mark_quarterbreeds_pdf', as: :print_mark_quarterbreeds_pdf
  get 'print-tr7s-pdf/:id' => 'tr7s#print_tr7_pdf', as: :print_tr7_pdf
  get 'print-quarterbreeds-pdf/:id' => 'quarterbreeds#print_quarterbreeds_pdf', as: :print_quarterbreeds_pdf
  get 'print-order-sheet-pdf/:id' => 'order_sheets#print_order_sheet_pdf', as: :print_order_sheet_pdf
  get 'print-datsun-zcar-pdf/:id' => 'datsun_zcars#print_datsun_zcar_pdf', as: :print_datsun_zcar_pdf

end

app/models/datsun_zcar.rb
class DatsunZcar < ActiveRecord::Base
  validates :vin, :car_owner_full_name, :car_owner_address, :car_owner_city, :car_owner_state, :car_owner_zip, presence: true


def set_datsun_zcar
  self.zcar_kit = 695
  self.save
end

def set_tach_calibration
  if self.tach_calibration == true
     self.tach_calibration_amt = 55
   else
      self.tach_calibration_amt = 0
  end
  self.save!
end

def set_tach_calibration_without_smog
  if self.tach_calibration_without_smog == true
     self.tach_calibration_without_smog_amt = 125
   else
      self.tach_calibration_without_smog_amt = 0
  end
  self.save!
end

def set_ramshorn_w_smog
  if self.ramshorn_w_smog == true
     self.ramshorn_w_smog_amt = 275
   else
      self.ramshorn_w_smog_amt = 0
  end
  self.save!
end

def set_ramshorn_w_egr_smog
  if self.ramshorn_w_egr_smog == true
     self.ramshorn_w_egr_smog_amt = 325
   else
      self.ramshorn_w_egr_smog_amt = 0
  end
  self.save!
end

def set_driveshaft_except_t400
  if self.driveshaft_except_t400 == true
     self.driveshaft_except_t400_amt = 165
   else
      self.driveshaft_except_t400_amt = 0
  end
  self.save!
end

def set_driveshaft_t400
  if self.driveshaft_t400 == true
     self.driveshaft_t400_amt = 205
   else
      self.driveshaft_t400_amt = 0
  end
  self.save!
end

def set_driveshaft_adaptor
  if self.driveshaft_adaptor == true
     self.driveshaft_adaptor_amt = 100
   else
      self.driveshaft_adaptor_amt = 0
  end
  self.save!
end

def set_radiator
  if self.radiator == true
     self.radiator_amt = 245
   else
      self.radiator_amt = 0
  end
  self.save!
end

def set_electric_fan
  if self.electric_fan == true
     self.electric_sfan_amt = 94.25
   else
      self.electric_sfan_amt = 0
  end
  self.save!
end

def set_electrolock_t700
  if self.electrolock_t700 == true
     self.electrolock_t700_amt = 85
   else
      self.electrolock_t700_amt = 0
  end
  self.save!
end

def set_subtotal
  self.subtotal = self.electrolock_t700_amt + self.electric_sfan_amt + self.zcar_kit + self.tach_calibration_amt + self.tach_calibration_without_smog_amt + self.ramshorn_w_smog_amt + self.ramshorn_w_egr_smog_amt + self.driveshaft_except_t400_amt + self.driveshaft_t400_amt + self.driveshaft_adaptor_amt + self.radiator_amt - self.credit_amt
  self.save!
end

def set_sales_tax
  if self.ship_to_state == "Texas"
    self.sales_tax = (self.subtotal) * (0.0825)
    self.sales_tax = self.sales_tax.round(2)
  else
    self.sales_tax = 0
  end
    self.save!
end

def set_total
  self.total = self.subtotal + self.sales_tax
  self.save
end

def set_same_shipping
  if self.same_information == true
    self.ship_to_full_name = self.car_owner_full_name
    self.ship_to_address = self.car_owner_address
    self.ship_to_city = self.car_owner_city
    self.ship_to_state = self.car_owner_state
    self.ship_to_zip = self.car_owner_zip
    self.ship_to_country = self.car_owner_country
    self.ship_to_email = self.car_owner_email
    self.ship_to_phone = self.car_owner_home_phone
    self.ship_to_fax = self.car_owner_fax
else
  end
  self.save
end

def set_home_phone
  if self.car_owner_home_phone.present?
    self.car_owner_home_phone.gsub!(/[^0-9]/, '')
    self.car_owner_home_phone.insert(3, '-').insert(7, '-')
  end
end

def set_work_phone
    if self.car_owner_work_phone.present?
      self.car_owner_work_phone.gsub!(/[^0-9]/, '')
      self.car_owner_work_phone.insert(3, '-').insert(7, '-')
    end
end

def set_ship_to_phone
    if self.ship_to_phone.present?
      self.ship_to_phone.gsub!(/[^0-9]/, '')
      self.ship_to_phone.insert(3, '-').insert(7, '-')
    end
end

def set_car_owner_fax
    if self.car_owner_fax.present?
      self.car_owner_fax.gsub!(/[^0-9]/, '')
      self.car_owner_fax.insert(3, '-').insert(7, '-')
    end
end

def set_ship_to_fax
    if self.ship_to_fax.present?
      self.ship_to_fax.gsub!(/[^0-9]/, '')
      self.ship_to_fax.insert(3, '-').insert(7, '-')
    end
end


end

app/controllers/datsun_zcars_controller.rb
class DatsunZcarsController < ApplicationController
  before_action :set_datsun_zcar, only:[:show, :edit, :update, :print_datsun_zcar_pdf]

  def new
    @datsun_zcar = DatsunZcar.new
  end

 def create
   @datsun_zcar = DatsunZcar.new(datsun_zcar_params)
   if @datsun_zcar.save
     redirect_to datsun_zcar_path(@datsun_zcar.id)
   else
     render :index
   end
 end

 def information
 end

 def index
   @datsun_zcar = DatsunZcar.new

 end

 def show
 end

 def print_datsun_zcar_pdf
   @datsun_zcar = DatsunZcar.find(params[:id])

   respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'file_name',
        :encoding => 'utf-8',
        :template => 'datsun_zcars/print_datsun_zcar_pdf.pdf.erb',
        :layout => 'pdf.html.erb',
        :show_as_html => params[:debug].present?
      end
    end
  end


 def edit
 end

 def update
   if @datsun_zcar.update(datsun_zcar_params)
     @datsun_zcar.save
     redirect_to datsun_zcar_path(@datsun_zcar.id)
   else
     render :edit
   end
 end


 private

 def datsun_zcar_params
   params.require(:datsun_zcar).permit(:car_owner_full_name, :car_owner_address, :car_owner_city, :car_owner_state, :car_owner_email, :car_owner_zip, :car_owner_home_phone, :car_owner_work_phone, :car_owner_fax, :car_owner_find_us, :car_owner_home_hours, :car_owner_work_hours, :car_owner_fax_hours, :car_owner_country, :car_owner_where_find_us, :ship_to_full_name, :ship_to_address, :ship_to_city, :ship_to_state, :ship_to_email, :ship_to_zip, :ship_to_phone, :ship_to_fax, :ship_to_contact_person, :ship_to_country, :same_information, :comments, :datsun_type, :vin, :year, :month_built, :year_built, :engine, :rear_axle, :tire_size, :power_steering, :zcar_kit, :tach_calibration, :tach_calibration_without_smog, :ramshorn_w_smog, :ramshorn_w_egr_smog, :driveshaft_except_t400, :driveshaft_t400, :radiator, :electric_fan, :electrolock_t700, :other, :credit_amt, :tach_calibration_amt, :tach_calibration_without_smog_amt, :ramshorn_w_smog_amt, :ramshorn_w_egr_smog_amt, :driveshaft_except_t400_amt, :driveshaft_t400_amt, :radiator_amt, :electric_sfan_amt, :electrolock_t700_amt, :other_amt, :credit_description, :subtotal, :expedite, :sales_tax, :total, :driveshaft_adaptor, :driveshaft_adaptor_amt, :rear_axl_ratio, :trans_type)
 end

 def set_datsun_zcar
    @datsun_zcar = DatsunZcar.find(params[:id])
    @datsun_zcar.set_datsun_zcar
    @datsun_zcar.set_tach_calibration
    @datsun_zcar.set_tach_calibration_without_smog
    @datsun_zcar.set_ramshorn_w_smog
    @datsun_zcar.set_ramshorn_w_egr_smog
    @datsun_zcar.set_driveshaft_except_t400
    @datsun_zcar.set_driveshaft_t400
    @datsun_zcar.set_driveshaft_adaptor
    @datsun_zcar.set_radiator
    @datsun_zcar.set_electric_fan
    @datsun_zcar.set_electrolock_t700
    @datsun_zcar.set_subtotal
    @datsun_zcar.set_sales_tax
    @datsun_zcar.set_total
    @datsun_zcar.set_same_shipping
    @datsun_zcar.set_home_phone
    @datsun_zcar.set_work_phone
    @datsun_zcar.car_owner_home_phone
    @datsun_zcar.set_ship_to_phone
    @datsun_zcar.set_car_owner_fax
    @datsun_zcar.set_ship_to_fax

 end
end

app/helpers/datsun_zcar_helper.rb
module DatsunZcarHelper
end

app/views/datsun_zcars/_information.html.erb
<div class="space-70"></div>
<div class="container">
<div class="panel panel-default" id="datsun_info">
    <div class="panel-heading" role="tab" id="headingOne">
      <h1 class="panel-title">
          <strong >ZCar V8 Conversions</strong>
      </h1>
    </div>
        <p>
          Chevy spunk for your Datsun ZCar.  John's Cars ZCar conversion to a Chevrolet V8 small block and GM transmission redefines <strong>AWESOME.</strong>  This 100% bolt-in kit does not rely on the stock Datsun crossmember motor mount towers alone for strength.  There is no welding required or recommended.  You do not drill holes in the frame or cut holes in the car as necessary with other swaps.  Front suspension mods are not usually needed due to engine setback.
        </p>
        <p>
          Stock exhaust manifolds can be used and the GM A6 A/C compressor fits.  We suggest you use a GM alternator and PS pump (as needed) rather than retain the $$$ ZCar units.  Transmission choices are: 4, 5 or 6-speed manual, T350, T400 or T700 overdrive automatics.  A V8 ZCar is approximately 2700 pounds, ZXCars slightly fatter!
        </p>
        <p>
          My kit for the 240-260-280Z or 280ZX includes:

        </p>
        <ul>
          <li>conversion mounting adapters</li>
          <li>engine rubber mounts</li>
          <li>transmission crossmember and mount</li>
          <li>throttle cable</li>
          <li>mechanical speedometer hookup and calibration</li>
          <li>water hoses and fittings</li>
          <li>oil pressure and water temperature hookups</li>
          <li>hardware and more</li>
          <li>illustrated instruction manual</li>
        </ul>
        <p>
          The installation requires approximately 40 hours exclusive of detailing.
        </p>

        <div class="space-70"></div>
        <div style="border-radius: 15px; border-color: red; border-style: solid; color: black; padding: 10px;">
          <h3 style="text-align: center;">
             <strong>SHOW ME, TELL ME</strong>
          </h3>
          <p>
            An abbreviated version of the conversion instructions are available for $25 - they will give you a good idea of the project and the $25 is credited to your kit purchase.          </p>
        </div>
        <div class="space-70"></div>
          <div class="row">
            <div class="col-xs-6 col-sm-6">
              <div class="services-box-smaller">
                <%= link_to "Back to top", anchor: ("v8_conversion"), class: "btn btn-primary"%>
              </div>
            </div>
            <div class="col-xs-6 col-sm-6">
              <div class="services-box-smaller">
                <%= link_to "Order Datsun Zcar Conversion Kit", new_datsun_zcar_path%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'datsun_zcars/recommendations' %>
<%= render partial: 'datsun_zcars/pricing' %>

app/views/datsun_zcars/_pricing.html.erb
<div class="container">
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingFive">
    <h1 class="panel-title">
        <strong>Pricing and How To Order</strong>
    </h1>
  </div>
      <p>
        Please fill out the three ZCar Conversion Kit Order Sheets completely, <strong>sign them</strong>, and return them with a <strong>money order or cashier's check</strong>.  No COD, no credit cards, no personal checks and no company checks are accepted on kit orders.  <em><strong>No exceptions!</em>  KITS are in STOCK and shipped upon receipt of funds.</strong>  Kit weight is approximately 36lbs.
      </p>
      <p>
        The order sheets are JPEG images (about 185K each) so it will take a minute or so to load.   Print it out from a Laser, LED or ink-jet printer only – dot matrix printer will be useless.  Make sure your print margins are set to .50 inches or it may not fit on a page.
      </p>
      <p>
        If you have any questions about the conversion, please call or email them to zcar@johnscars.com.  Prices subject to change without notice.
      </p>
      <p>
        Read our Customer Testimonials to hear what our customers think about us and our products.
      </p>
      <p>
        <strong><em>Note:</strong> Given the proprietary nature of my conversion kits, I do not allow the return of a conversion kit for any reason.</em>
      </p>
      <table class="table table-bordered">
        <thead>
          <th colspan=2> V8 ZCar Kit & Goodies </th>
          <th> Price</th>
          <th>Freight</th>
        </thead>
        <tbody>
          <tr>
            <td class="col-md-2"><strong>V8 ZCar Kit</strong></td>
            <td class="col-md-6"></td>
            <td class="col-md-2"><strong>$695.00</strong></td>
            <td class="col-md-2"><strong>Paid</strong></td>
          </tr>
          <tr>
            <td class="col-md-2"><strong>Show Me, Tell Me</strong></td>
            <td class="col-md-6"> A abbreviated version of the conversion manual is available for you to preview and is credited toward your kit purchase.</td>
            <td class="col-md-2">$25.00</td>
            <td class="col-md-2">Paid</td>
          </tr>
          <tr>
            <td><strong>Tachometer Recalibration</strong> </td>
            <td>(send it to me) <small>1</small></td>
            <td>$55.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td><strong>Ramshorn Exhaust Manifolds</strong> </td>
            <td>Pair for Small Blocks</td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td>...Without Smog (AIR) fittings - used <small>2, 3</small></td>
            <td>$125.00</td>
            <td>$15.00</td>
          </tr>
          <tr>
            <td></td>
            <td>With Smog (AIR) fittings - new <small>2, 3</small></td>
            <td>$275.00</td>
            <td>$15.00</td>
          </tr>
          <tr>
            <td></td>
            <td>With EGR setup and Smog (AIR) fittings (LT-1 only) <small>2</small></td>
            <td>$325.00</td>
            <td>$15.00</td>
          </tr>
          <tr>
            <td></td>
            <td><strong>Air Rail Set</strong> for Ramshorn Manifolds - pair</td>
            <td>$45.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td></td>
            <td><strong>Check Valves</strong> for Air Rails - pair</td>
            <td>$35.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td><strong>Driveshafts</strong>	</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td>T350 or T700 Driveshaft (without adapter) <small>2</small></td>
            <td>$165.00</td>
            <td>$13.00</td>
          </tr>
          <tr>
            <td></td>
            <td>T400 Heavy Duty Driveshaft (without adapter) <small>2</small></td>
            <td>$205.00</td>
            <td>$13.00</td>
          </tr>
          <tr>
            <td><strong>Driveshaft Adapter</strong> </td>
            <td>GM to Datsun <small>2</small></td>
            <td>$100.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td><strong>Fuel Injection Stuff</strong> </td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td> </td>
            <td>TBIPUMP - fuel pump for TBI injection</td>
            <td>$115.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td> </td>
            <td>TPIPUMP - fuel pump for TPI and LT-1</td>
            <td>$172.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td> </td>
            <td>Oxygen Sensor Bungs</td>
            <td>$6.00</td>
            <td>$1.00</td>
          </tr>
          <tr>
            <td><strong>Electric Fan</strong> </td>
            <td>16" with built-in shroud <small>2</small></td>
            <td>$94.25</td>
            <td>$10.00</td>
          </tr>
          <tr>
            <td> <strong>Fanstat</strong> </td>
            <td>electric fan controller</td>
            <td>$40.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td><strong>Radiator</strong></td>
            <td>Super-Duty 4 Row  - exchange only <small>2</small></td>
            <td>$245.00</td>
            <td>$18.00</td>
          </tr>
          <tr>
            <td><strong>Electrolock™</strong>  </td>
            <td>torque convertor lockup for T700</td>
            <td>$85.00</td>
            <td>$5.00</td>
          </tr>
          <tr>
            <td><strong>Cable X</strong>  </td>
            <td>mechanical speedo output for 6-speed manual</td>
            <td>$375.00</td>
            <td>$7.00</td>
          </tr>
          <tr>
            <td colspan=4> <strong><small>1</small></strong>	 Non-JCI Conversion - Tach calibration is $70.00.</td>
          </tr>
          <tr>
            <td colspan=4> <strong><small>2</small></strong> Add $50.00 to these items if your V8 ZCar is not a JCI Kit.</td>
          </tr>
          <tr>
            <td colspan=4> <strong><small>3</small></strong> Add $30.00 to manifolds to fit FI motors with center bolt valve covers</td>
          </tr>
          <tr>
            <td colspan=4> <strong><small>AIR</small></strong>--air induction reaction <br>
              All freight overages will be refunded.
            </td>
          </tr>
        </tbody>
      </table>
      <div class="space-70"></div>
      <div class="row">
        <div class="col-xs-6 col-sm-6">
          <div class="services-box-smaller">
            <%= link_to "Back to top", anchor: ("v8_conversion"), class: "btn btn-primary"%>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6">
          <div class="services-box-smaller">
            <%= link_to "Order Datsun Zcar Conversion Kit", new_datsun_zcar_path%>
          </div>
        </div>
      </div>
    <!-- </div> -->
  <!-- </div> -->
</div>
</div>

app/views/datsun_zcars/_recommendations.html.erb
<div class="container">
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingTwo">
    <h1 class="panel-title">
        <strong>Recommendations</strong>
    </h1>
  </div>

      <div class="col-md-2">
        <h4> Motors </h4>
      </div>
      <div class="col-md-10">
        <p>
          Stock small block motors provide a vast improvement over Datsun power no matter how hipo a 6-cylinder you build. Use a 305 (5.0) for fuel economy or a 350 (5.7) for more punch. Other V8 sizes, 327, 383, 400 (small block) etc. are also suitable.
         </p>
        <p>
          <strong>Fuel Injection (FI):</strong> For years we’ve suggested carb motors to keep it simple, however, GM has the bugs worked out and we are ready when you are. Four OEM systems are available, throttle body injection (TBI) that uses a carb looking unit with two centrally located injectors, tuned port injection (TPI) with an injector at each port, the high revving LT-1, and the Vortec V8 motor. All of these FI systems work great with a JCI Conversion Kit.
         </p>
         <p>
           FI is not a cheap date, but you’ll have class <strong>provided</strong> you don’t try to shortcut the job. A JCI Conversion Kit <strong><em>DOES NOT</em></strong> include the Fuel Injection harness, ECM, fuel pump or associated wiring and plumbing that is FI related. You must buy a custom harness (or modify an original harness) from the aftermarket FI guys (we do not sell or customize FI harnesses). There are many businesses that sell tech manuals, complete harnesses, programmed ECMs, etc.  Here are two we use:
         </p>
         <p>
           Howell Engine Development in Michigan 810-765-5100
           Dr. K in Alabama 205-543-7165
         </p>
         <p>
           <strong>LT-1 Notes:</strong> LT-1 passenger car brackets will not clear the engine mounts and frame of the ZCar.  You must use Corvette LT-1 brackets.  The LT-1 and 4300 derivative have the EGR plumbed externally into the rear of the intake because GM deleted the exhaust crossover passage in the heads.  On the LT-1, it is best to keep the EGR because it reduces spark knock, reduces emissions, and allows the computer to signal more ignition advance (better performance).  I have a pair of exhaust manifolds with the required modifications, parts, and plumbing necessary to retain the EGR.   AIR - air induction reaction - is also accommodated with these manifolds (a must in communities with emission controls requirements).  AIR only functions the first minute or so of operation - it helps complete combustion and light off the catalytic converters quicker.  The air pump on LT-1 is electric and is controlled by the ECM.
         </p>
         <p>
           <strong>Fuel Injection $$$:</strong>  Add a $100.00 to the JCI Kit Price when using a FI V8 motor for the many changes required for this V8 kit – cooling system, electrical, steering and A/C plumbing, etc. plus 8 more pages of instructions.
         </p>
      </div>
      <div class="col-md-2">
        <h4> Transmissions: </h4>
      </div>
      <div class="col-md-10">
        <p>
          I suggest you use an T700 automatic transmission in your V8 ZCar as it is an automatic slightly easier swap and with mountains of torque available it is really a more driveable car.  You can light 'em up whenever you want and the 30% overdrive reduces noise, improves mileage and lengthens engine life.  The automatic shifter from another ZCar is my preference or use an aftermarket custom shifter. T700 requires a one inch dent in tunnel.  Please, do yourself a favor and install a T700 overdrive the first time.
        </p>
        <p>
          <strong>T700 Notes:</strong>   All T700's have torque-convertor lockup and it <strong>must be hooked up</strong> to prevent damage to the transmission.  John's Cars offers <strong>ELECTROLOCK™</strong>, the simple set-up to lock-up a T700 torque convertor for maximum fuel economy. Very easy to install – no drilling, tapping or machining required.  For T700 trans to 1992 (not 4L60E).  The kit can be installed with the trans in the car.
        </p>
        <p>
          If a manual transmission is a must for you, then use an overdrive!  Manual transmission installations are likely to require enlarging the hole in the tunnel for the shifter and reworking console. The T5 is your best combination for availability and reliability.  If you desire the 6-speed from later GM cars, the only obstacle is its lack of a mechanical speedometer output - but we've got the answer.
        </p>
      </div>
      <div class="col-md-2">
        <h4>Exhaust Manifolds:</h4>
      </div>
      <div class="col-md-10">
        <p>
          We use Ramshorn Exhaust manifolds (as illustrated).  You can get them at your local dealer (GM #372243) or we sell them.
        </p>
      </div>
      <br clear="all"/>
      <div class="col-md-2">
        <h4> Driveshaft: </h4>
      </div>
      <div class="col-md-10">
        <p>
          I strongly recommend my special driveshaft adapter that permits using an all GM driveshaft with full size U-Joints on each end. Shortening a GM driveshaft costs $15.00-$30.00. A kluged GM-Datsun driveshaft will cost you $100.00-$200.00 and will be the weak link you want to avoid.
        </p>
      </div>
      <div class="col-md-2">
        <h4> Notes: </h4>
      </div>
      <div class="col-md-10">
        <p>
          If your Z is rusty, please find another one. The front frame rails were subject to rusting, and it is not worth the chance of what would happen if it should succumb to the torque of the new power plant.  The Z rear axle has proven adequate for most applications.
        </p>
      </div>
      <div class="col-md-2">
        <h4> Suggestion: </h4>
      </div>
      <div class="col-md-10">
        <p>
          I <strong><em>strongly</em></strong> recommend you purchase a <strong>COMPLETE</strong> "pull-out" engine with transmission, fan, all accessories and brackets, trans oil cooler lines, air filter assembly (with a flat top), etc., as a package.  Buying a piece at a time will drive you and the parts person nuts, not to mention the added time and money.  Alternatively, consider also buying an older but complete Chevrolet car and rebuilding the motor, transmission, etc. Performance mods are easy to do at overhaul time.  I suggest 1969-up long style water pump and brackets, internal regulator alternator and HEI distributor.  The main point is to get the new driveline <strong>COMPLETE</strong> – even if you have to buy an entire car to do it!  This is the number one comment from people who try to piece it together themselves.
        </p>
      </div>
      <div class= "col-md-12" style="border-radius: 15px; border-color: yellow; border-style: solid; color: black; padding: 10px;">
        <div class="col-md-2" >
          <h4> California SMOG: </h4>
        </div>
        <div class="col-md-10">
          <p>
            In January 1998, sanity prevailed and the emission laws changed, and now imply that all cars 25 or more years old are exempt from emissions standards.  Please check with your local authorities!
          </p>
        </div>
      </div>

      <div class="space-70"></div>
      <div class="row">
        <div class="col-xs-6 col-sm-6">
          <div class="services-box-smaller">
            <%= link_to "Back to top", anchor: ("v8_conversion"), class: "btn btn-primary"%>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6">
          <div class="services-box-smaller">
            <%= link_to "Order Datsun Zcar Conversion Kit", new_datsun_zcar_path%>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/datsun_zcars/edit.html.erb
<%= render partial: "datsun_zcars/form" %>

app/views/datsun_zcars/new.html.erb
<%= render partial: "datsun_zcars/form" %>

app/views/datsun_zcars/show.html.erb
<br><br><br><br>
<div class="container">
  <p> Your Datsun Zcar Order form was generated correctly. <%= link_to "Click Here", print_datsun_zcar_pdf_path(@datsun_zcar.id, format: :pdf) %> to print your order form. </p>
  <br><br>
  <p> Need to Edit your Datsun Zar order form? <%= link_to "Click Here", edit_datsun_zcar_path(@datsun_zcar.id) %> to edit your form. </p>
</div>