config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :order_sheets
  resources :quarterbreeds
    get "quarterbreed/information" => "quarterbreeds#information", as: :quarterbreed_information

  resources :tr7s
  resources :mark_quarterbreeds
  resources :xj6_quarterbreeds
  resources :etype_v12s

  resources :datsun_zcars
    get "datsun_zcar/information" => "datsun_zcars#information", as: :datsun_zcar_information

  get 'jaguars' =>'pages#jaguars', as: :jaguars
  get 'xj-sedans' => 'jaguars#xj_sedans', as: :xj_sedans
  get 'triumph-tr7' => 'pages#triumph_tr7', as: :triumph_tr7
  get 'chevy-v8' => 'pages#chevy_v8', as: :chevy_v8

  get 'order_forms' => 'pages#order_forms', as: :order_forms
  get 'home2' => 'pages#home2', as: :home2
  get 'print-etype-v12/:id' => 'etype_v12s#print_etype_v12_pdf', as: :print_etype_v12_pdf
  get 'print-xj6-quarterbreeds-pdf/:id' => 'xj6_quarterbreeds#print_xj6_pdf', as: :print_xj6_pdf
  get 'print-mark-quarterbreeds-pdf/:id' => 'mark_quarterbreeds#print_mark_quarterbreeds_pdf', as: :print_mark_quarterbreeds_pdf
  get 'print-tr7s-pdf/:id' => 'tr7s#print_tr7_pdf', as: :print_tr7_pdf
  get 'print-quarterbreeds-pdf/:id' => 'quarterbreeds#print_quarterbreeds_pdf', as: :print_quarterbreeds_pdf
  get 'print-order-sheet-pdf/:id' => 'order_sheets#print_order_sheet_pdf', as: :print_order_sheet_pdf
  get 'print-datsun-zcar-pdf/:id' => 'datsun_zcars#print_datsun_zcar_pdf', as: :print_datsun_zcar_pdf

end

app/views/pages/chevy_v8.html.erb
<%= render partial: "jaguars/why_convert_jag_to_chevy" %>

<%= render partial: "jaguars/which_engine_to_use" %>
<%= render partial: "jaguars/smog_requirements" %>
<%= render partial: "jaguars/best_transmission" %>
<%= render partial: "jaguars/chevy_v8_price" %>
<%= render partial: "jaguars/why_buy_johns_kit" %>
<%= render partial: "jaguars/whats_included" %>

app/views/pages/datsun_zcar.html.erb
<div class="space-30"></div>
<div class="space-30"></div>

<section id="content-region-1" class="padding-40">
    <div class="container">
        <div class="row">
            <div class="col-md-12 features">
                <h3>Datsun ZCar</h3>
                <div class="row panel panel-default">
                    <div class="col-md-3 services-icon">
                        <%= image_tag("zcar.png", :class => "car-pic") %>
                    </div>
                    <div class="col-md-9 services-text">
                        <h4 class="heading-mini">Datsun ZCar</h4>
                        <p>The Datsun ZCar was the first Japanese sports car to gain acceptance in America. </p>
                        <div class=" col-sm-9">
                        <div class="services-box">
                            <h4><%= link_to "ZCar V8 Conversion", root_path%></h4>
                            <p>   Chevy spunk for your Datsun ZCar. John's Cars ZCar conversion to a Chevrolet V8 small block and GM transmission redefines <strong><em>AWESOME</em></strong>.  Stock exhaust manifolds can be used and the GM A6 A/C compressor fits. We suggest you use a GM alternator and PS pump (as needed) rather than retain the $$$ ZCar units. Transmission choices are 4, 5 or 6-speed manual, T350, T400 or T700 overdrive automatics.</p>
                        </div>
                        </div> <!--col6-->
                        <div class=" col-sm-9">
                        <div class="services-box">
                            <h4>ZCar Parts</h4>
                            <p> This is the extent of our Zcar offerings, we do not have brakes, suspension, frame etc components nor do we have any experience with other companies parts.</p>
                        </div>
                        </div> <!--col6-->
                      
                    </div>
                </div><!--row panel-->
              </div>    <!--col 12-->
    </div><!--row-->
  </div><!--container-->
</section>

app/views/pages/home2.html.erb
<section id="slider-sec" class="slider-reg">
    <div class="main-flex-slider">
        <ul class="slides">
            <li>
                <figure>
                  <%= image_tag("jag_car.png", :class => "img-responsive") %>
                    <figcaption class="slider-overlay ">
                        <div class="slider-text animated fadeInDown">
                            <h1>John's Cars</h1>
                            <p>  Making Jaguars RAD – Reliable, Affordable and Driveable  </p>
                            <%= link_to "Order Now", order_forms_path, class: "btn btn-white btn-lg" %>
                            <!-- <p class="slide-btn"><a href="#" class="btn btn-white btn-lg">Order Now</a></p> -->
                        </div>
                    </figcaption>
                </figure>
            </li>
        </ul>
    </div>
</section><!--main flex slider end-->
        <div class="space-50"></div>
        <div class="container">
            <div class="row intro-row">
                <div class="col-md-12 text-center wow animated fadeInUp">
                    <h2>	Welcome to John's Cars </h2>
                    <h3 class="subtitle">Home of those wonderfully British cars with American drivelines. </h3>
                </div>
                <div class="space-70"></div>
                <div class=" col-sm-4">
                    <div class="services-box">
                        <%= link_to jaguars_path do %>
                          <i class="ion-android-car"></i>
                        <% end %>
                        <h1>Jaguar Conversions</h1><br>
                        <p>
                            Want to put an American motor and/or transmission in your Jaguar?  It's a snap with John's Cars conversion.  Kits are available for the Classic XJ Sedans ( XJ6C, XJ6L, XJ12C, XJ12L), the XJS Coupe and Convertibles, the Mark Series, and the legendary E-Type.
                        </p>
                    </div>
                </div><!--services box-->
                <div class=" col-sm-4">
                    <div class="services-box">
                      <%= link_to ('http://www.brokenkitty.com/') do %>
                        <i class="ion-wrench"></i>
                      <% end %>
                        <h1>Jaguar Parts</h1><br>
                        <p>
                            Need parts for your Jaguar?  Have problems you need to diagnose?  Check out our new on-line Broken Kitty Catalog - the best place to find parts and advice on the web.  New, rebuilt, used and aftermarket are all available and ready to ship.  Place your order online with our easy-to-use, secure shopping cart.
                        </p>
                    </div>
                </div><!--services box-->
                <div class="col-sm-4">
                    <div class="services-box">
                      <%= link_to triumph_tr7_path do %>
                      <i class="ion-android-car"></i>
                      <% end %>
                        <h1>Triumph TR7</h1><br>
                        <p>
                            Salvation for the anemic TR7: a John’s Cars conversion will provide you with the oomph you deserve (more than a TR8) and saves your Triumph from being on the way to the lonely boneyard.  We also have some TR7 parts.
                        </p>
                    </div>
                </div><!--services box-->
              </div><!--row end-->
              <div class="row intro-row">
                <div class="col-sm-4">
                    <div class="services-box">
                      <%= link_to datsun_zcars_path do %>
                      <i class="ion-android-car"></i>
                      <% end %>

                        <h1>Datsun ZCar</h1><br>
                        <p>
                          Redefine AWESOME with a John's Cars ZCar Chevy V8 conversion.  Our bolt-in kit will breathe new life into the original Datsun sports car. We do not carry any non V8 conversion.
                        </p>
                    </div>
                </div><!--services box-->

              </div>  <!--row-->
        </div><!--intro with services end-->
        <div class="space-70"></div><div class="space-30"></div>







                    </div>
                </div>

            </div><!--container-->
        </section><!--features end-->
<%= render partial: "layouts/footer"%>

app/views/pages/index.html.erb
<section id="slider-sec" class="slider-reg">
    <div class="main-flex-slider">
        <ul class="slides">
            <li>
                <figure>
                  <%= image_tag("XKE_WhiteSands.JPG", :class => "img-responsive") %>
                    <figcaption class="slider-overlay ">
                        <div class="slider-text animated fadeInDown">
                            <h1>John's Cars</h1>
                            <p>  Making Jaguars RAD – Reliable, Affordable and Driveable  </p>
                            <div class="space-30"></div>
                            <div class="row">
                              <div class=" col-xs-4 col-xs-offset-2">
                                <div class="services-box-smaller">
                                  <h5><%= link_to "Jaguar Conversions", jaguars_path %></h5>
                                </div>
                              </div>
                              <div class="col-xs-4">
                                <div class="services-box-smaller">
                                  <h5><%= link_to "Jaguar Parts", ('http://www.brokenkitty.com/')%></h5>
                                </div>
                              </div><!--services box-->
                            </div>
                              <div class="row">
                                <div class="col-xs-4 col-xs-offset-2">
                                  <div class="services-box-smaller">
                                    <h5><%= link_to "Triumph TR7", triumph_tr7_path%></h5>
                                  </div>
                                </div><!--services box-->
                                <div class="col-xs-4">
                                  <div class="services-box-smaller">
                                    <h5><%= link_to "Datsun ZCar", datsun_zcars_path %></h5>
                                  </div>
                                </div><!--services box-->
                              </div>
                        </div>
                      </figcaption>
                </figure>
            </li>``
        </ul>
      </div>
    </section>

<!-- <section id="content-region-2" class="parallax-1"> -->
  <!-- <div style="background-color:white; opacity: 0.8;">
      <div class="row">
          <div class="col-md-12 text-center">
              <div class="testimonials">
                  <ul class="slides">
                      <li class="flex-active-slide" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 1; display: block; z-index: 2;">
                        <p class="testi-text">"I am 50 years old and have a bachelor's degree in civil and mining engineering.  I have been a street rodder for better than 25 years... My street rodding background has made me painfully aware of the expense of having to manufacture all of your own brackets, hoses, etc...  In my opinion, your kit is still cheaper at twice the price...  Thanks again, both for making the kit available and for being so helpful on the phone.  The conversion turned what had been a dog into a real cat..."<span class="testi-person">Chester Stevens, Hazard, KY  </span>
                          </p>
                      </li>
                  </ul>
              <ol class="flex-control-nav flex-control-paging">
                <li>
                  <a class="">1</a>
                </li>
                <li><a class="flex-active">2</a>
                </li>
                <li><a class="">3</a>
                </li>
              </ol>
            </div>
          </div>
      </div>
  </div> -->
  <!-- <div class="space-70"></div>
  <div class="space-70"></div>
  <div class="space-70"></div> -->

    <!-- <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 features" style="background-color: white; opacity: 0.9; border-radius: 25px;">
                <h1>Jaguar Parts</h1>
                <p style="font-weight:800;">
                    Need parts for your Jaguar?  Have problems you need to diagnose?  Check out our new on-line Broken Kitty Catalog - the best place to find parts and advice on the web.  New, rebuilt, used and aftermarket are all available and ready to ship.  Place your order online with our easy-to-use, secure shopping cart.
                </p>
                <div class="space-30"></div>
                <div class="row">
                    <div class="col-md-3 services-icon">
                        <i class="ion-ios-paper-outline"></i>
                    </div>
                    <div class="col-md-9 services-text">
                        <h4 class="heading-mini">The Big Step</h4>
                        <p style="font-weight:800;">
                            Before laying out the big money for anyone’s conversion kit, buy the BIG STEP, a complete guide to preparing for a V8 conversion for your Jaguar.  It includes:
                        </p>
                    </div> -->
                <!-- </div><!-services list-->
                <!-- <div class="space-30"></div>
                <div class="row">
                    <div class="col-md-3 services-icon">
                      <i class="ion-compose"></i>
                    </div>
                    <div class="col-md-9 services-text">
                        <h4 class="heading-mini">News</h4>
                        <p style="font-weight:800;">
                            Trying to keep up with the latest from John's Cars?  Read John's monthly ramble in Hemmings.  He'll discuss various asundry things and even occasionally tries to sell parts.  Now there's an idea!  Honestly, most of his stories are humorous and there are tidbits of information hidden within – including diagnostic tips, parts specials, even jabs at our competitors and nay-sayers occasionally (read them closely!).
                        </p>
                    </div> -->
                <!-- </div><!-services list-->
                <!-- <div class="space-30"></div>
                <div class="row">
                    <div class="col-md-3 services-icon">
                      <i class="ion-social-usd"></i>
                    </div>
                    <div class="col-md-9 services-text">
                        <h4 class="heading-mini">Specials</h4>
                        <p style="font-weight:800;">
                            Discover the latest specials from John's Cars.
                        </p>
                    </div> -->
                <!-- </div><!-services list-->
                <!-- <div class="space-30"></div>
            </div>
        </div> -->
    <!-- </div><!-container-->
    <!-- <div class="space-70"></div> -->

<!-- </section><!-features end-->
<!-- </section> -->

<%= render partial: "layouts/footer" %>

app/views/pages/jaguars.html.erb
<section id="slider-sec" class="slider-reg">
    <div class="main-flex-slider" id="triumph_top">
        <ul class="slides">
            <li>
                <figure>
                   <%= image_tag("XKE_Mayfeast.JPG", :class => "img-responsive") %>

                    <figcaption class="slider-overlay ">
                        <div class="slider-text animated fadeInDown">
                            <h1>Jaguar Conversions</h1>
                            <p>  Making Jaguars RAD – Reliable, Affordable and Driveable  </p>
                          <div class="space-30"></div>
                        </div>
                        <div class="row">
                          <div class=" col-xs-6 col-sm-4 col-sm-offset-2">
                            <div class="services-box-smaller" >
                              <h5><%= link_to "XJ Sedans", xj_sedans_path(anchor: "xj_sedans") %></h5>
                            </div>
                          </div> <!--col4-->
                          <div class="col-xs-6 col-sm-4">
                            <div class="services-box-smaller">
                              <h5><%= link_to "XJS & XJS HE", jaguars_path(anchor: "xjs_and_xjs_he") %></h5>
                            </div>
                          </div><!--services box-->
                        </div>
                        <div class="row">
                          <div class="col-xs-6 col-sm-4 col-sm-offset-2">
                            <div class="services-box-smaller">
                              <h5><%= link_to "E-TYPE", jaguars_path(anchor: "e_type") %></h5>
                            </div>
                          </div><!--services box-->
                          <div class="col-xs-6 col-sm-4">
                            <div class="services-box-smaller">
                              <h5><%= link_to "MARK SEDANS", jaguars_path(anchor: "mark_sedans") %></h5>
                            </div>
                          </div><!--services box-->
                        </div>
                    </figcaption>
                </figure>
            </li>
        </ul>
      </div>
    </section>

    <!-- XJ Sedans  -->
    <div id="xj_sedans">
      <%= render partial: "jaguars/xj_sedans" %>
    </div>

    <!-- XJS & XJS He Sedans  -->
    <div id="xjs_and_xjs_he">
      <%= render partial: "jaguars/xjs_and_xjs_he" %>
    </div>

    <!-- E-Type  -->
    <div id="e_type">
      <%= render partial: "jaguars/e_type" %>
    </div>

    <!-- Mark Sedans  -->
    <div id="mark_sedans">
      <%= render partial: "jaguars/mark_sedans" %>
    </div>

    <%= render partial: "layouts/footer" %>


<!-- <section id="content-region-1" class="padding-40"> -->
    <!-- <div class="container">
        <div class="row">
            <div class="col-md-12 features">
                <h3>Jaguar Conversions</h3>
                <p>Which conversion are you looking for?  Just click a conversion or item next to the car that looks like yours.  Or click the Jaguar to go to more information about that model.
                </p> -->
                <!-- <div class="row panel panel-default">
                    <div class="col-md-3 services-icon">
                        <%= image_tag("xj_sedans.png", :class => "car-pic") %>
                    </div>
                    <div class="col-md-9 services-text">
                        <h4 class="heading-mini">XJ Sedans (1969 to 1987)</h4>
                        <p>The classic Jaguar Sedan was built for 20 years in many variations (XJ6, XJ6C, XJ6L, XJ12, XJ12C, and XJ12L).  We define the "classic" XJ Sedans as all sedans from 1969 to 1987 in the USA (Series 3 XJ12 sedans were available through 1992 in the ROW [rest of the world]).    Check out the <%= link_to"XJ Sedan Model Guide", root_path%> for more details. </p>
                        <div class=" col-sm-6">
                        <div class="services-box">
                            <h4><%= link_to "Chevy V8 Conversion", root_path%></h4>
                            <p>   Ready to drive your Sedan there-and-back without visiting the shop?  A Chevy V8 driveline provides the reliability and driveability you have been waiting for!</p>
                        </div> -->
                      <!-- </div> <!-col6-->
                      <!-- <div class=" col-sm-6">
                      <div class="services-box">
                          <h4><%= link_to "XJ6 Quarterbreed", root_path%></h4>
                          <p> Got the Borg-Warner blues?  Replace it with a reliable and sturdy GM transmission.</p>
                      </div> -->
                    <!-- </div> <!-col6-->
                    <!-- <div class=" col-sm-6">
                    <div class="services-box">
                        <h4><%= link_to "XJ12 Quarterbreed", root_path%></h4>
                        <p> Tired of third gear?  LEAP into the 21st century with a GM overdrive behind your V12 Jaguar motor.</p>
                    </div> -->
                  <!-- </div> <!-col6-->
                  <!-- <div class=" col-sm-6">
                  <div class="services-box">
                      <h4><%= link_to "XJ Sedan parts", root_path%></h4>
                      <p> We carry a full line of parts for all XJ Sedan models – new, rebuilt and used.</p>
                  </div> -->
                <!-- </div> <!-col6-->
              <!-- </div> -->
            <!-- </div><!-services list-->
                <!-- <div class="space-30"></div>
                <div class="row panel panel-default"> -->
                    <!-- <div class="col-md-3 services-icon">
                      <%= image_tag("xjs_he.png", :class => "car-pic") %>
                    </div> -->
                    <!-- <div class="col-md-9 services-text"> -->
                        <!-- <h4 class="heading-mini">XJS & XJS HE (1976 to 1996)</h4> -->
                        <!-- <p>The replacement for the E-Type, the Jaguar XJS matched the XJ Sedans in longevity and in variations (XJS, XJS-HE, XJ-SC [Cabriolet], XJS Convertible).  Check out the <%= link_to "XJS Model Guide", root_path%> for more details.</p> -->
                        <!-- <div class=" col-sm-4">
                          <div class="services-box"> -->
                              <!-- <h5><%= link_to "XJS Chevy V8 Conversion", root_path%></h5> -->
                              <!-- <p> Make your XJS what it was meant to be – a luxury sports car.   A Chevy conversion will make your XJS fun to drive – reliability is a side effect.  Fits all XJS.</p> -->
                          <!-- </div>
                        </div>
                        <div class=" col-sm-4">
                          <div class="services-box"> -->
                              <!-- <h5><%= link_to "XJS Quarterbreed", root_path%></h5> -->
                              <!-- <p> Tired of third gear?  LEAP into the 21st century with a GM overdrive behind your V12 Jaguar motor.  Fits all V12 XJS.</p> -->
                          <!-- </div>
                        </div>
                        <div class=" col-sm-4">
                          <div class="services-box"> -->
                              <!-- <h5><%= link_to "XJS & XJS HE Parts", root_path%></h5> -->
                              <!-- <p> We carry a full line of parts for all XJS models – new, rebuilt and used.  Check out</p> -->
                          <!-- </div>
                        </div>
                    </div> -->
                <!-- </div><!-services list-->
                <!-- <div class="space-30"></div>
                  <div class="row panel panel-default">
                      <div class="col-md-3 services-icon"> -->
                        <!-- <%= image_tag("e-type.png", :class => "car-pic text-center") %> -->
                      <!-- </div>
                    <div class="col-md-9 services-text"> -->
                        <!-- <h4 class="heading-mini">E-Type (1961 to 1974)</h4> -->
                        <!-- <p> -->
                          <!-- The sexiest car ever made is even more fun with a V8 under the hood.  Make it a daily driver rather than a toy for the weekends. -->
                        <!-- </p>
                        <div class=" col-sm-4">
                          <div class="services-box"> -->
                              <!-- <h5><%= link_to "V12 E-Type to Chevy V8 Conversion", root_path%></h5> -->
                              <!-- <p> Chevrolet small block spunk and reliability for the sexiest cars ever built.  Fits all V12 E-Types (1971 to 1974).</p>
                          </div>
                        </div>
                        <div class=" col-sm-4"> -->
                          <!-- <div class="services-box"> -->
                              <!-- <h5><%= link_to "6-cylinder E-Type to Ford V8 Conversion", root_path%></h5> -->
                              <!-- <p> Put a Chevy transmission behind your 6-cylinder Jaguar motor.  Fits all 6-cylinder E-Types (1961 to 1971).</p>
                          </div>
                        </div>
                        <div class=" col-sm-4">
                          <div class="services-box">
                              <h5><%= link_to "E-Type Parts", root_path%></h5>
                              <p> We have most suspension and brake parts for the E-Types.</p>
                          </div>
                        </div>
                    </div>
                  </div> -->
                    <!-- <div class="space-30"></div>

                    <div class="row panel panel-default">
                      <div class="col-md-3 services-icon"> -->
                        <!-- <%= image_tag("mark_sedans.png", :class => "car-pic") %> -->
                      <!-- </div>
                    <div class="col-md-9 services-text"> -->
                        <!-- <h4 class="heading-mini">Mark Sedans (1955 to 1969)</h4> -->
                        <!-- <p> -->
                            <!-- The ancestors of the XJ Sedan, these classics suffer from many of the same motor and transmission woes of its descendants.  The Mark came in several models, including the Mark I, II, IX, X, 240,340, 420 and S-Types. -->
                        <!-- </p> -->
                        <!-- <div class=" col-sm-4"> -->
                          <!-- <div class="services-box"> -->
                              <!-- <h5><%= link_to "Mark GM V6 Conversion", root_path%></h5> -->
                              <!-- <p> A GM V6 and overdrive transmission make the Mark classic feel at home the modern world.  Fits the Mark I, Mark II, S-Types and 420 (does not fit the others).</p> -->
                          <!-- </div> -->
                        <!-- </div> -->
                        <!-- <div class=" col-sm-4"> -->
                          <!-- <div class="services-box"> -->
                              <!-- <h5><%= link_to "Mark Quarterbreed", root_path%></h5> -->
                              <!-- <p> LEAP into the 21st century with a Chevy overdrive transmission while keeping the 6-cylinder Jaguar motor.  Fits all Mark Models.</p> -->
                          <!-- </div> -->
                        <!-- </div> -->
                        <!-- <div class=" col-sm-4"> -->
                          <!-- <div class="services-box"> -->
                              <!-- <h5><%= link_to "Mark Parts", root_path%></h5> -->
                              <!-- <p> We have a limited selection of mechanical parts for the Mark Series.</p> -->
                          <!-- </div> -->
                        <!-- </div> -->
                    <!-- </div> -->
                    <!-- </div -->
                <!-- </div><!-services list-->
              <!-- </div>
            </div> -->
          </section>

app/views/pages/order_forms.erb
<div class="container">
  <div class="space-70"></div>
  <div class="space-70"></div>
  <li><%= link_to "JCI LS ZCAR KIT", order_sheets_path %></li>
   <li><%= link_to "JCI V12 QUARTERBREED", quarterbreeds_path%></li>
  <li><%= link_to "TR7 KIT ", tr7s_path%></li>
  <li><%= link_to "MARK QUARTERBREED ", mark_quarterbreeds_path%></li>
  <li><%= link_to "XJ6 QUARTERBREED ", xj6_quarterbreeds_path%></li>
  <li><%= link_to "Etype V12 ", etype_v12s_path%></li>
  <li><%= link_to "Datsun Zcar ", new_datsun_zcar_path%></li>


</div>


<section id="content-region-1" class="padding-40">
    <div class="container">
      <div class="row">
            <div class="col-md-12 features">
              <div class="row panel panel-default">
                <div class="col-sm-3 services-icon" id="v8_conversion">
                    <%= image_tag("e-type.png", :class => "car-pic text-center") %>
                </div>
                <div class="col-sm-4 services-text">
                  <h4 class="heading-mini">EType V12</h4>
                  <p>The sexiest car ever made is even more fun with a V8 under the hood. Make it a daily driver rather than a toy for the weekends.</p>
                </div>
                <div class="col-sm-4">
                  <br>
                  <br>
                  <div class="services-box-smaller" >
                    <h5><%= link_to "EType V12", etype_v12s_path %></h5>
                  </div>
                </div> <!--col4-->
            </div>

        </div>
      <div class="row">
            <div class="col-md-12 features">
              <div class="row panel panel-default">
                  <div class="col-md-3 services-icon" id="v8_conversion">
                      <%= image_tag("zcar.png", :class => "car-pic") %>
                  </div>
                  <div class="col-md-9 services-text">
                    <h4 class="heading-mini">Datsun ZCar</h4>
                    <p>The Datsun ZCar was the first Japanese sports car to gain acceptance in America.</p>
                    <div class="row">
                      <div class=" col-xs-6 col-sm-6">
                        <div class="services-box-smaller" >
                          <h5><%= link_to "ZCar V8 Conversion", anchor: ("datsun_info") %></h5>
                        </div>
                      </div> <!--col4-->
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</section>