config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :order_sheets
  resources :quarterbreeds
    get "quarterbreed/information" => "quarterbreeds#information", as: :quarterbreed_information

  resources :tr7s
  resources :mark_quarterbreeds
  resources :xj6_quarterbreeds
  resources :etype_v12s

  resources :datsun_zcars
    get "datsun_zcar/information" => "datsun_zcars#information", as: :datsun_zcar_information

  get 'jaguars' =>'pages#jaguars', as: :jaguars
  get 'xj-sedans' => 'jaguars#xj_sedans', as: :xj_sedans
  get 'triumph-tr7' => 'pages#triumph_tr7', as: :triumph_tr7
  get 'chevy-v8' => 'pages#chevy_v8', as: :chevy_v8

  get 'order_forms' => 'pages#order_forms', as: :order_forms
  get 'home2' => 'pages#home2', as: :home2
  get 'print-etype-v12/:id' => 'etype_v12s#print_etype_v12_pdf', as: :print_etype_v12_pdf
  get 'print-xj6-quarterbreeds-pdf/:id' => 'xj6_quarterbreeds#print_xj6_pdf', as: :print_xj6_pdf
  get 'print-mark-quarterbreeds-pdf/:id' => 'mark_quarterbreeds#print_mark_quarterbreeds_pdf', as: :print_mark_quarterbreeds_pdf
  get 'print-tr7s-pdf/:id' => 'tr7s#print_tr7_pdf', as: :print_tr7_pdf
  get 'print-quarterbreeds-pdf/:id' => 'quarterbreeds#print_quarterbreeds_pdf', as: :print_quarterbreeds_pdf
  get 'print-order-sheet-pdf/:id' => 'order_sheets#print_order_sheet_pdf', as: :print_order_sheet_pdf
  get 'print-datsun-zcar-pdf/:id' => 'datsun_zcars#print_datsun_zcar_pdf', as: :print_datsun_zcar_pdf

end

app/models/quarterbreed.rb
class Quarterbreed < ActiveRecord::Base
    validates :jaguar_vin, :car_owner_full_name, :car_owner_address, :car_owner_city, :car_owner_state, :car_owner_zip, presence: true



    def set_quarterbreed_kit
      self.quarterbreed_kit = 895
      self.save
    end

    def set_driveshaft
      if self.draveshaft == true
         self.driveshaft_amt = 265
       else
          self.driveshaft_amt = 0
      end
      self.save!
    end

    def set_flywheel_core
      if self.flywheel_core == true
         self.flywheel_core_amt = 200
       else
          self.flywheel_core_amt = 0
      end
      self.save!
    end

    def set_subtotal
      self.subtotal = self.quarterbreed_kit + self.driveshaft_amt +   self.flywheel_core_amt - self.credit
      self.save!
    end

    def set_sales_tax
      if self.ship_to_state == "Texas"
        self.sales_tex = (self.subtotal) * (0.0825)
        self.sales_tex
      else
        self.sales_tex = 0
      end
        self.save
    end

    def set_total
      self.total = self.subtotal + self.sales_tex
    end

    def set_same_shipping
      if self.same_information == true
        self.ship_to_full_name = self.car_owner_full_name
        self.ship_to_address = self.car_owner_address
        self.ship_to_city = self.car_owner_city
        self.ship_to_state = self.car_owner_state
        self.ship_to_zip = self.car_owner_zip
        self.ship_to_email = self.car_owner_email
        self.ship_to_phone = self.car_owner_home_phone
        self.ship_to_fax = self.car_owner_fax
        self.ship_to_countr = self.car_owner_countr
      end
    end

    def set_home_phone
      if self.car_owner_home_phone.present?
        self.car_owner_home_phone.gsub!(/[^0-9]/, '')
        self.car_owner_home_phone.insert(3, '-').insert(7, '-')
      end
    end

    def set_work_phone
        if self.car_owner_work_phone.present?
          self.car_owner_work_phone.gsub!(/[^0-9]/, '')
          self.car_owner_work_phone.insert(3, '-').insert(7, '-')
        end
    end

    def set_ship_to_phone
        if self.ship_to_phone.present?
          self.ship_to_phone.gsub!(/[^0-9]/, '')
          self.ship_to_phone.insert(3, '-').insert(7, '-')
        end
    end

    def set_car_owner_fax
        if self.car_owner_fax.present?
          self.car_owner_fax.gsub!(/[^0-9]/, '')
          self.car_owner_fax.insert(3, '-').insert(7, '-')
        end
    end

    def set_ship_to_fax
        if self.ship_to_fax.present?
          self.ship_to_fax.gsub!(/[^0-9]/, '')
          self.ship_to_fax.insert(3, '-').insert(7, '-')
        end
    end

end

app/controllers/quarterbreeds_controller.rb
class QuarterbreedsController < ApplicationController
  before_action :set_quarterbreed, only:[:show, :edit, :update, :print_quarterbreeds_pdf]

  def new
    @quarterbreed = Quarterbreed.new
  end

 def create
   @quarterbreed = Quarterbreed.new(quarterbreed_params)
   if @quarterbreed.save
     redirect_to quarterbreed_path(@quarterbreed.id)
   else
     render :index
   end
 end

 def index
    @quarterbreed = Quarterbreed.new
 end

 def information
 end

 def show
 end

 def print_quarterbreeds_pdf
   respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'file_name',
        :encoding => 'utf-8',
        :template => 'quarterbreeds/print_quarterbreeds_pdf.pdf.erb',
        :layout => 'pdf.html.erb',
        :show_as_html => params[:debug].present?
      end
    end
  end

 def edit
 end

 def update
   if @quarterbreed.update(quarterbreed_params)
     @quarterbreed.save
     redirect_to quarterbreed_path(@quarterbreed.id)
   else
     render :edit
   end
 end




 private

 def quarterbreed_params
   params.require(:quarterbreed).permit(:car_owner_full_name, :car_owner_address, :car_owner_city, :car_owner_state, :car_owner_email, :car_owner_zip, :car_owner_home_phone, :car_owner_work_phone, :car_owner_fax, :car_owner_find_us, :car_owner_home_hours, :car_owner_work_hours, :car_owner_fax_hours, :ship_to_full_name, :ship_to_address, :ship_to_city, :ship_to_state, :ship_to_email, :ship_to_zip, :ship_to_phone, :ship_to_fax, :ship_to_contact_person, :jaguar_type, :jaguar_vin, :jaguar_year, :jaguar_month_built, :jugaur_year_built, :engine_number, :engine_type, :tire_size, :tire_radius, :rear_axie_ratio, :speedo_number, :jaguar_trans, :flywheel_core, :draveshaft, :credit, :subtotal, :sales_tex, :texas_resident, :expedite, :total, :comments, :flywheel_core_amt, :driveshaft_amt, :quarterbreed_kit, :same_information, :car_owner_countr, :ship_to_countr, :car_owner_where_find_us, :other_speedo, :rear_axle_ratio_other)
 end

 def set_quarterbreed
   @quarterbreed = Quarterbreed.find(params[:id])
   @quarterbreed.set_same_shipping
   @quarterbreed.set_quarterbreed_kit
   @quarterbreed.set_driveshaft
   @quarterbreed.set_flywheel_core
   @quarterbreed.set_subtotal
   @quarterbreed.set_sales_tax
   @quarterbreed.set_total
   @quarterbreed.set_home_phone
   @quarterbreed.set_work_phone
   @quarterbreed.set_ship_to_phone
   @quarterbreed.set_car_owner_fax
   @quarterbreed.set_ship_to_fax
 end


end

app/helpers/quarterbreeds_helper.rb
module QuarterbreedsHelper
end

app/views/quarterbreeds/_form.html.erb
<div class="container">
  <%= simple_form_for(@quarterbreed) do |f| %>
  <%= f.error_notification %>
  <br><br><br><br>
  <h2 class="text-center"> JCI V12 QUARTERBREED KIT ORDER SHEET </h2>
  <p> Please complete as much information as you can - there are thousands of variations of my kits. Phone numbers and Vehicle Identification Number (VIN) (serial number) are essential. Incomplete or <em> unsigned </em> forms will delay your order! We require payment in advance by <b> Cashier's Check or Money Order </b> in U.S. currency. <b> NO CODs</b>, personal checks, company checks, credit cards or wire transfers. <b> KITS ARE NOT RETURNABLE.</b> </p>

  <div class="panel panel-default col-md-6">
  <h3 class="text-center">Jaguar Information</h3>
   <div class="row">
       <div class="col-md-12">
         <p class="p-form hint"> The Vehicle Identification Number (VIN) is located on window pillar or base on windshield in front of driver's door.</p>
         <p class="hint"> Year/ Month are located on the driver's door or jamb.</p>
       </div>
       <div class="col-md-4">
         <h4>Model Year</h4>
         <%= f.input :jaguar_year, label: false, placeholder:"Year", collection: ["1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996"]%>
       </div>
       <div class="col-md-4">
         <h4>Type </h4>
         <%= f.input :jaguar_type, label: false, placeholder:"Type",  collection: ["XJ12", "XJ12 Series III", "XJ12C", "XJ12L", "XJS", "XJS-HE", "XJ-SC", "V12 Etype", "Streetrod/Custom car", "Other - fill out in comments"]%>
       </div>
       <div class="col-md-4">
         <h4>VIN #</h4>
         <%=f.input :jaguar_vin , label: false,  placeholder:"" %>
      </div>
   </div row>
   <div class="row">

     <div class="col-md-4">
          <h4>Month Built </h4>
          <%= f.input :jaguar_month_built, label: false, placeholder:"Month Built", collection: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
          %>
      </div>
     <div class="col-md-4">
          <h4>Year Built </h4>
          <%= f.input :jugaur_year_built, label: false, placeholder: "Year Built", collection: ["1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996"]%>
      </div>
    </div row>
    <br>
    <h3 class="text-center"> Engine Information</h3>
    <div class="row">
      <div class="col-md-12">
        <p class="p-form hint"> Engine Number is located at bell
          housing flange of engine, in the top center.</p>
        <p class="p-form hint">Rear Axle Ratio: Tag under bolt on rear cover, sometimes shown in ratio form (49/17).</p>
      </div>
      <div class="col-md-6">
           <h4>Engine #</h4>
           <%= f.input :engine_number, label: false, placeholder: ""%>
       </div>
       <div class="col-md-6">
            <h4>Engine Model </h4>
            <%= f.input :engine_type, label: false, placeholder: "", collection: ["Carbureted", "Fuel Injection"]%>
        </div>
       </div row>
       <br>
       <div class="row">
         <div class="col-md-6">
              <h4>Tire Size </h4>
              <%= f.input :tire_size, label: false, placeholder: "Tire Size"%>
          </div>
         <div class="col-md-6">
              <h4>Tire Radius </h4>
              <%= f.input :tire_radius, label: false, placeholder: "Tire Radius"%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
               <h4>Rear Axle Ratio</h4>
               <%= f.input :rear_axie_ratio, label: false, placeholder: "", collection: ["2.88", "3.08", "3.31", "3.54", "Other - fill out in the next box"]%>
               </h4>
           </div>
           <div class="col-md-6">
                <h4>Rear Axle Ratio Other</h4>
                <%= f.input :rear_axle_ratio_other, label: false, placeholder: ""%>
                </h4>
            </div>
         </div>



 </div><!--panel-->

 <div class="panel panel-default col-md-6">
   <h3 class="text-center">Transmission Information</h3>
   <div class="col-md-12">
        <p class="p-form hint"> Speedo Number:  I need the 3 or 4 numbers in fine print located along the bottom edge of the speedometer "face" (between 5 & 6 o'clock) on most cars, near the center on early cars.</p>
   </div>
   <div class="row">
     <div class="col-md-6">
       <div class="text-center">
          <%= image_tag('pic1.png') %>
      </div text center>
    </div col6>
     <div class="col-md-6">
       <h4> Current Transmission </h4>
       <%= f.input :jaguar_trans, label: false, placeholder: "Current Transmission", collection: ["Borg Warner", "T400"]%>
     </div>
   </div row>
     <div class="row">
       <div class="col-md-4">
         <div class="text-center">
            <%= image_tag('speedo2.png') %>
          </div>
        </div>
         <div class="col-md-4">
            <h4>Speedo # </h4>
            <%= f.input :speedo_number, label: false, placeholder: "", collection: ["940", "1000", "1020", "Other - fill out in next box"]%>
        </div>
        <div class="col-md-4">
          <h4> Other Speedo </h4>
          <%= f.input :other_speedo, label: false, placeholder: "Unique Speedo Number" %>
        </div>
      </div>
 <h3 class="text-center"> MONIES </h3>
  <table class="table table-bordered">
    <tbody>
      <td class="col-md-4"> V12 T700 </td>
      <td class="col-md-4"> </td>
      <td class="col-md-4"><strong> $895.00 </strong></td>
      <tr>
        <td class="col-md-4">T400 Flywheel Core Deposit </td>
        <td class="col-md-4"> $200.00 </td>
        <td class="col-md-4"><%= f.collection_radio_buttons :flywheel_core, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
      </tr>
      <tr>
        <td class="col-md-4">Complete balanced driveshaft </td>
        <td class="col-md-4"> $265.00 </td>
        <td class="col-md-4"><%= f.collection_radio_buttons :draveshaft, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
      </tr>
      <tr>
        <td class="col-md-4">Credit  <br> <small>* Price is Required (if no credit put "0")</small></td>
        <td class="col-md-4">(Non-illustrated or Repeat Kits) </td>
        <td class="col-md-4"> Price <%= f.input :credit, label: false, placeholder:"Required, must be a positive number" %> </td>
      </tr>
      <tr>
        <td class="col-md-4">Are you a Texas Resident? </td>
        <td class="col-md-4"> Add Sales Tax -- 8.25% </td>
        <td class="col-md-4"> </td>
      </tr>
      <!-- <tr>
        <td class="col-md-4">Hawaii or Expedite </td>
        <td class="col-md-4"> (Overnite or 2 day) </td>
        <td class="col-md-4"> < f.collection_radio_buttons :expedite, [[true, 'Yes'], [false, 'No']], :first, :last%> </td>
      </tr> -->
    </tbody>
  </table>
</div>
<br clear="all">


     <div class="panel panel-default col-md-6">
    <h2 class="text-center"> Car Owner Information  </h2>
    <div class="row">
      <div class="col-md-4">
        <h4> Name </h4>
        <%= f.input :car_owner_full_name, label: false,  placeholder:"Full Name" %>
      </div>
      <div class="col-md-4">
        <h4>Address </h4>
        <%= f.input :car_owner_address, label: false,  placeholder:"Address" %>
      </div>
      <div class="col-md-4">
        <h4> City</h4>
        <%= f.input :car_owner_city, label: false,  placeholder:"City" %>
      </div>
      <div class="col-md-4">
        <h4> State</h4>
        <%= f.input :car_owner_state, collection: ["None", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" ], label: false,  placeholder:"State" %>
      </div>
      <div class="col-md-4">
        <h4>Zip </h4>
        <%= f.input :car_owner_zip, label: false,  placeholder:"Zip" %>
      </div>
      <div class="col-md-4">
        <h4>Country </h4>
        <%= f.input :car_owner_countr, label: false,  placeholder:"Country" %>
      </div>


      <div class="col-md-4">
        <h4>Email </h4>
        <%= f.input :car_owner_email, label: false,  placeholder:"Email" %>
      </div>
      <div class="col-md-4">
        <h4> Home Phone</h4>
        <%= f.input :car_owner_home_phone, label: false,  placeholder:"(###) ### - ####" %>
      </div>
      <div class="col-md-4">
        <h4> Home Hours </h4>
        <%= f.input :car_owner_home_hours, label: false,  placeholder:"From xx to xx" %>
      </div>
      <div class="col-md-4">
        <h4>Work Phone </h4>
        <%= f.input :car_owner_work_phone, label: false,  placeholder:"(###) ### - ####" %>
      </div>
      <div class="col-md-4">
        <h4> Work  Hours </h4>
        <%= f.input :car_owner_work_hours , label: false,  placeholder:"From xx to xx" %>
      </div>
      <div class="col-md-4">
        <h4>Fax </h4>
        <%= f.input :car_owner_fax, label: false,  placeholder:"(###) ### - ####" %>
      </div>
      <div class="col-md-4">
        <h4> Fax Hours </h4>
        <%= f.input :car_owner_fax_hours , label: false,  placeholder:"From xx to xx" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>How did you find us </h4>
        <%= f.input :car_owner_find_us , label: false,  placeholder:"",  priority: [ "Internet" ], collection: [ "Internet", "Magazine", "WOM", "Hybridz", "Shop Referal", "Car Show", "Magazine Article", "Other"] %>
      </div>
      <div class="col-md-6">
        <h4>Which magazine, WOM, Internet or ??? </h4>
        <%= f.input :car_owner_where_find_us , label: false,  placeholder:""%>
      </div>
    </div row>
  </div>

  <div class="panel panel-default col-md-6">
      <h2 class="text-center"> Shop or "Ship To" Information  </h2>
      <br>
      <p class="p-form"> Is the shipping information the same as the car owner information? (REQUIRED)</p>
      <%= f.collection_radio_buttons :same_information, [[true, 'Yes'] ,[false, 'No']], :first, :last  %> </p>
      <div class="row">
        <div class="col-md-4">
          <h4> Name </h4>
          <%= f.input :ship_to_full_name, label: false,  placeholder:"Full Name" %>
        </div>
        <div class="col-md-4">
          <h4>Address </h4>
          <%= f.input :ship_to_address, label: false,  placeholder:"Address" %>
        </div>
        <div class="col-md-4">
          <h4> City</h4>
          <%= f.input :ship_to_city, label: false,  placeholder:"City" %>
        </div>
        <div class="col-md-4">
          <h4> State</h4>
          <%= f.input :ship_to_state,  collection: ["None", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island","South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" ] , label: false,  placeholder:"State" %>
        </div>
        <div class="col-md-4">
          <h4>Zip </h4>
          <%= f.input :ship_to_zip, label: false,  placeholder:"Zip" %>
        </div>
        <div class="col-md-4">
          <h4>Country </h4>
          <%= f.input :ship_to_countr, label: false,  placeholder:"Country" %>
        </div>

        <div class="col-md-4">
          <h4>Email </h4>
          <%= f.input :ship_to_email, label: false,  placeholder:"Email" %>
        </div>
        <div class="col-md-4">
          <h4>Shop Phone </h4>
          <%= f.input :ship_to_phone, label: false,  placeholder:"(###) ### - ####" %>
        </div>
        <div class="col-md-4">
          <h4>Shop Fax </h4>
          <%= f.input :ship_to_fax, label: false,  placeholder:"(###) ### - ####" %>
        </div>
        <div class="col-md-4">
          <h4>Contact Person </h4>
          <%= f.input :ship_to_contact_person, label: false,  placeholder:"Contact Person" %>
        </div>
      </div row>
    </div>


    <div class="col-md-12">
        <p> The V12 QUARTERBREED Conversion kit is the  property of John's Cars, Inc., including the design, parts and procedures; All Rights Reserved. This Conversion Kit is for the purchaser's personal use and not to be duplicated in whole or in part even if altered. Please check with local authorities regarding emission controls where required. John's Cars, Inc. assumes no liability regarding purchaser's installation or use. </p>
       <h4>Additional comments or notes </h4>
       <%= f.input :comments, label: false, placeholder:"" %>
       <%= f.submit "PRINT ORDER", { class: 'btn btn-danger btn-lg btn-block' }%>
          <br>
          <br>
        </div>

  <% end %>
  <br>
  <br>
</div>

app/views/quarterbreeds/edit.html.erb
<%= render partial: 'form'%>

app/views/quarterbreeds/index.html.erb
<%= render partial: 'form'%>

app/views/quarterbreeds/new.html.erb
<%= render partial: 'form'%>

app/views/quarterbreeds/show.html.erb
<br><br><br><br>
<div class="container">
  <p> Your V12 Quarterbreed form was generated correctly. <%= link_to "Click Here", print_quarterbreeds_pdf_path(@quarterbreed.id, format: :pdf) %> to print your order form. </p>
  <br><br>
  <p> Need to Edit your V12 Quarterbreed order form? <%= link_to "Click Here", edit_quarterbreed_path(@quarterbreed.id) %> to edit your form. </p>
</div>