config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :order_sheets
  resources :quarterbreeds
    get "quarterbreed/information" => "quarterbreeds#information", as: :quarterbreed_information

  resources :tr7s
  resources :mark_quarterbreeds
  resources :xj6_quarterbreeds
  resources :etype_v12s

  resources :datsun_zcars
    get "datsun_zcar/information" => "datsun_zcars#information", as: :datsun_zcar_information

  get 'jaguars' =>'pages#jaguars', as: :jaguars
  get 'xj-sedans' => 'jaguars#xj_sedans', as: :xj_sedans
  get 'triumph-tr7' => 'pages#triumph_tr7', as: :triumph_tr7
  get 'chevy-v8' => 'pages#chevy_v8', as: :chevy_v8

  get 'order_forms' => 'pages#order_forms', as: :order_forms
  get 'home2' => 'pages#home2', as: :home2
  get 'print-etype-v12/:id' => 'etype_v12s#print_etype_v12_pdf', as: :print_etype_v12_pdf
  get 'print-xj6-quarterbreeds-pdf/:id' => 'xj6_quarterbreeds#print_xj6_pdf', as: :print_xj6_pdf
  get 'print-mark-quarterbreeds-pdf/:id' => 'mark_quarterbreeds#print_mark_quarterbreeds_pdf', as: :print_mark_quarterbreeds_pdf
  get 'print-tr7s-pdf/:id' => 'tr7s#print_tr7_pdf', as: :print_tr7_pdf
  get 'print-quarterbreeds-pdf/:id' => 'quarterbreeds#print_quarterbreeds_pdf', as: :print_quarterbreeds_pdf
  get 'print-order-sheet-pdf/:id' => 'order_sheets#print_order_sheet_pdf', as: :print_order_sheet_pdf
  get 'print-datsun-zcar-pdf/:id' => 'datsun_zcars#print_datsun_zcar_pdf', as: :print_datsun_zcar_pdf

end

app/models/order_sheet.rb
class OrderSheet < ActiveRecord::Base
  validates :zcar_vin, :car_owner_full_name, :car_owner_address, :car_owner_city,
:car_owner_state, :car_owner_zip, presence: true


  def set_add_mount_set
    if self.add_mount_set == "Yes"
      self.mount_set = 295
    elsif self.add_mount_set == "No, I already bought this"
      self.mount_set = 0
    else self.add_mount_set == "Not JCI car parts"
      self.mount_set = 0
    end
    self.save!

  end

  def set_trans_crossmember
    if self.trans_crossmember == true
      self.amt1 = 135
    else
      self.amt1 = 0
    end
    self.save!
  end

  def set_driveshaft
    if self.driveshaft == true
       self.amt2 = 255
     else
        self.amt2 = 0
    end
    self.save!
  end

  def set_speedometer
    if self.speedometer == true
       self.amt3 = 345
    else
      self.amt3 = 0
    end
    self.save!
  end

  def set_vital_liquids
    if self.vital_liquids == true
       self.amt4 = 105
    else
       self.amt4  = 0
    end
       self.save!

  end

  def set_header_set
    if self.header_set == true
       self.amt5 = 385
    else
       self.amt5  = 0
    end
     self.save!
  end

  def set_ac_compressor_mount_kit
    if self.ac_compressor_mount_kit == true
       self.amt6 = 450
    else
       self.amt6  = 0
    end
     self.save!
  end

  def set_ac_hose_kit
    if self.ac_hose_kit == true
       self.amt7 = 200
    else
       self.amt7  = 0
    end
     self.save!
  end

  def set_high_volume
    if self.high_volume == true
       self.amt8 = 165
    else
        self.amt8 = 0
    end
       self.save!
  end

  def set_subtotal
    self.subtotal = self.mount_set + self.amt1 + self.amt2 + self.amt3 + self.amt4 + self.amt5 + self.amt6 + self.amt7 + self.amt8
    self.save!
  end

  def set_sales_tax
    if self.ship_to_state == "Texas"
      self.sales_tax = (self.subtotal) * (0.0825)
      self.sales_tax
    else
      self.sales_tax = 0
    end
      self.save
  end

  def set_total
    self.total = self.subtotal + self.sales_tax
  end

  def set_same_shipping
    if self.same_information == true
      self.ship_to_full_name = self.car_owner_full_name
      self.ship_to_address = self.car_owner_address
      self.ship_to_city = self.car_owner_city
      self.ship_to_state = self.car_owner_state
      self.ship_to_zip = self.car_owner_zip
      self.ship_to_countr = self.car_owner_countr
      self.ship_to_email = self.car_owner_email
      self.ship_to_phone = self.car_owner_home_phone
      self.ship_to_fax = self.car_owner_fax
      self.ship_to_countr = self.car_owner_countr
    end
  end

  def set_home_phone
    if self.car_owner_home_phone.present?
      self.car_owner_home_phone.gsub!(/[^0-9]/, '')
      self.car_owner_home_phone.insert(3, '-').insert(7, '-')
    end
  end

  def set_work_phone
      if self.car_owner_work_phone.present?
        self.car_owner_work_phone.gsub!(/[^0-9]/, '')
        self.car_owner_work_phone.insert(3, '-').insert(7, '-')
      end
  end

  def set_ship_to_phone
      if self.ship_to_phone.present?
        self.ship_to_phone.gsub!(/[^0-9]/, '')
        self.ship_to_phone.insert(3, '-').insert(7, '-')
      end
  end

  def set_car_owner_fax
      if self.car_owner_fax.present?
        self.car_owner_fax.gsub!(/[^0-9]/, '')
        self.car_owner_fax.insert(3, '-').insert(7, '-')
      end
  end

  def set_ship_to_fax
      if self.ship_to_fax.present?
        self.ship_to_fax.gsub!(/[^0-9]/, '')
        self.ship_to_fax.insert(3, '-').insert(7, '-')
      end
  end

end

app/controllers/order_sheets_controller.rb
class OrderSheetsController < ApplicationController
   before_action :set_order_sheet, only:[:show, :edit, :update, :print_order_sheet_pdf]

   def new
     @order_sheet = OrderSheet.new
   end

  def create
    @order_sheet = OrderSheet.new(order_sheet_params)
    if @order_sheet.save
      redirect_to order_sheet_path(@order_sheet.id)
    else
      render :index
    end
  end

  def index
     @order_sheet = OrderSheet.new
  end

  def show
  end

  def print_order_sheet_pdf
    respond_to do |format|
       format.html
       format.pdf do
         render :pdf => 'file_name',
         :encoding => 'utf-8',
         :template => 'order_sheets/print_order_sheet_pdf.pdf.erb',
         :layout => 'pdf.html.erb',
         :show_as_html => params[:debug].present?
       end
     end
   end

  def edit
  end

  def update
    if @order_sheet.update(order_sheet_params)
      @order_sheet.save
      redirect_to order_sheet_path(@order_sheet.id)
    else
      render :edit
    end
  end


  private

  def order_sheet_params
    params.require(:order_sheet).permit(:car_owner_full_name, :car_owner_address, :car_owner_city, :car_owner_state, :car_owner_email, :car_owner_zip, :car_owner_home_phone, :car_owner_work_phone, :car_owner_fax, :car_owner_find_us, :car_owner_home_hours, :car_owner_work_hours, :car_owner_fax_hours, :ship_to_full_name, :ship_to_address, :ship_to_city, :ship_to_state, :ship_to_email, :ship_to_zip, :ship_to_phone, :ship_to_fax, :ship_to_contact_person, :zcar_type, :zcar_vin, :zcar_year, :zcar_month_built, :zcar_year_built, :trans_crossmember, :driveshaft, :speedometer, :vital_liquids, :header_set, :ac_compressor_mount_kit, :ac_hose_kit, :high_volume, :subtotal, :sales_tax, :total, :sign_date, :same_information, :ship_to_countr, :comments, :hole_size, :pilot_diameter, :pattern_type, :transmission_type, :transmission_detail, :amt2, :amt1, :amt3, :amt4, :amt5, :amt6, :amt7, :amt8, :amt9, :ls_type, :ls_year, :rh_monies, :car_owner_countr, :mount_set, :zcar_type2, :ls_type2, :car_owner_where_find_us, :other_differential_flange, :q45, :output_shaft, :add_mount_set, :transmission_year, :transmission_other, :credit_amt)
  end

  def set_order_sheet
    @order_sheet = OrderSheet.find(params[:id])
    @order_sheet.set_add_mount_set
    @order_sheet.set_trans_crossmember
    @order_sheet.set_driveshaft
    @order_sheet.set_speedometer
    @order_sheet.set_vital_liquids
    @order_sheet.set_header_set
    @order_sheet.set_ac_compressor_mount_kit
    @order_sheet.set_ac_hose_kit
    @order_sheet.set_high_volume
    @order_sheet.set_same_shipping
    @order_sheet.set_subtotal
    @order_sheet.set_sales_tax
    @order_sheet.set_total
    @order_sheet.set_home_phone
    @order_sheet.set_work_phone
    @order_sheet.set_ship_to_phone
    @order_sheet.set_car_owner_fax
    @order_sheet.set_ship_to_fax
  end

end

app/helpers/order_sheets_helper.rb
module OrderSheetsHelper
end

app/views/order_sheets/edit.html.erb
<%= render partial: 'form' %>

app/views/order_sheets/index.html.erb
<div class="container">
  <%= simple_form_for(@order_sheet) do |f| %>
  <h2 class="text-center default-form"> JCI LS ZCAR ORDER SHEET </h2>
  <p> Please complete as much information as you can. Phone numbers and Vehicle Identification Number (VIN) (serial number) are essential. Illegible, incomplete or <em> unsigned </em> forms will delay your order! We require payment in advance by <b> Cashier's Check or Money Order </b> in U.S. currency. <b> NO COD's</b>, no personal or company checks, no credit cards and no wire transferes. <b> PARTS ARE NOT RETURNABLE.</b> </p>
  <div class="row">
    <div class="col-md-3">
      <h4> LS Type </h4>
      <%= f.input :ls_type, label: false, placeholder:"",  priority: [ "LS1" ], collection: [ "LS1", "LS2", "LS3", "LS7"] %>
    </div>
    <div class="col-md-3">
      <h4> Year </h4>
      <%= f.input :ls_year, label: false, placeholder:"LS Year" %>
    </div>
  </div>

  <h2 class="text-center default-form"> Car Owner Information  </h2>
  <div class="row">
    <div class="col-md-3">
      <h4> Name </h4>
      <%= f.input :car_owner_full_name, label: false,  placeholder:"Full Name" %>
    </div>
    <div class="col-md-3">
      <h4>Address </h4>
      <%= f.input :car_owner_address, label: false,  placeholder:"Address" %>
    </div>
    <div class="col-md-3">
      <h4> City</h4>
      <%= f.input :car_owner_city, label: false,  placeholder:"City" %>
    </div>
    <div class="col-md-3">
      <h4> State</h4>
      <%= f.input :car_owner_state, label: false,  placeholder:"State" %>
    </div>
    <div class="col-md-3">
      <h4>Zip </h4>
      <%= f.input :car_owner_zip, label: false,  placeholder:"Zip" %>
    </div>
    <div class="col-md-3">
      <h4>Email </h4>
      <%= f.input :car_owner_email, label: false,  placeholder:"Email" %>
    </div>
    <div class="col-md-3">
      <h4> Home Phone</h4>
      <%= f.input :car_owner_home_phone, label: false,  placeholder:"Home Phone" %>
    </div>
    <div class="col-md-3">
      <h4> Home Phone Hours Available</h4>
      <%= f.input :car_owner_home_hours, label: false,  placeholder:"From xx to xx" %>
    </div>
    <div class="col-md-3">
      <h4>Work Phone </h4>
      <%= f.input :car_owner_work_phone, label: false,  placeholder:"Work Phone" %>
    </div>
    <div class="col-md-3">
      <h4> Work Phone Hours Available</h4>
      <%= f.input :car_owner_work_hours , label: false,  placeholder:"From xx to xx" %>
    </div>
    <div class="col-md-3">
      <h4>Fax </h4>
      <%= f.input :car_owner_fax, label: false,  placeholder:"Fax" %>
    </div>
    <div class="col-md-3">
      <h4> Fax Hours Available</h4>
      <%= f.input :car_owner_fax_hours , label: false,  placeholder:"From xx to xx" %>
    </div>

    <div class="col-md-3">
      <h4>How did you find us </h4>
      <%= f.input :car_owner_find_us , label: false,  placeholder:"",  priority: [ "Internet" ], collection: [ "Internet", "Magazine", "WOM", "Other"] %>
    </div>
  </div row>

    <h2 class="text-center default-form"> Shop or "Ship To" Information  </h2>
    <p> Is the shipping information the same as the car owner information </p>
    <%= f.collection_radio_buttons :same_information, [[true, 'Yes'] ,[false, 'No']], :first, :last  %> </p>
    <div class="row">
      <div class="col-md-3">
        <h4> Name </h4>
        <%= f.input :ship_to_full_name, label: false,  placeholder:"Full Name" %>
      </div>
      <div class="col-md-3">
        <h4>Address </h4>
        <%= f.input :ship_to_address, label: false,  placeholder:"Address" %>
      </div>
      <div class="col-md-3">
        <h4> City</h4>
        <%= f.input :ship_to_city, label: false,  placeholder:"City" %>
      </div>
      <div class="col-md-3">
        <h4> State</h4>
        <%= f.input :ship_to_state, label: false,  placeholder:"State" %>
      </div>
      <div class="col-md-3">
        <h4>Zip </h4>
        <%= f.input :ship_to_zip, label: false,  placeholder:"Zip" %>
      </div>
      <div class="col-md-3">
        <h4>Country </h4>
        <%= f.input :ship_to_countr, label: false,  placeholder:"Country" %>
      </div>
      <div class="col-md-3">
        <h4>Email </h4>
        <%= f.input :ship_to_email, label: false,  placeholder:"Email" %>
      </div>
      <div class="col-md-3">
        <h4>Shop Phone </h4>
        <%= f.input :ship_to_phone, label: false,  placeholder:"Shop Phone" %>
      </div>
      <div class="col-md-3">
        <h4>Shop Fax </h4>
        <%= f.input :ship_to_fax, label: false,  placeholder:"Shop Fax" %>
      </div>
      <div class="col-md-3">
        <h4>Contact Person </h4>
        <%= f.input :ship_to_contact_person, label: false,  placeholder:"Contact Person" %>
      </div>
    </div row>

  <h2 class="text-center default-form"> ZCar Info (Before V8)
   </h2>
   <div class="row">
     <div class="col-md-3">
       <h4>Type </h4>
       <%=f.input :zcar_type , label: false,  placeholder:"",  priority: [ "240" ], collection: [ "240", "260", "280Z", "not 280ZX", "2 + 2"] %>
     </div>
     <div class="col-md-3">
       <h4>VIN NUMBER </h4>
       <%= f.input :zcar_vin, label: false, placeholder:"Window pillar in front of driver's door"%>
     </div>
     <div class="col-md-3">
       <h4>Year </h4>
       <%= f.input :zcar_year, label: false, placeholder:"Year"%>
     </div>
     <div class="col-md-3">
          <h4>Year Built </h4>
          <%= f.input :zcar_year_built, label: false, placeholder:"Located on driver's door or jamb"%>
      </div>
     <div class="col-md-3">
          <h4>Month Built </h4>
          <%= f.input :zcar_month_built, label: false, placeholder:"Month Built"%>
      </div>
   </div row>

   <h2 class="text-center default-form"> Differentail Flange Details</h2>
   <div class="row">
     <div class="text-center">
        <%= image_tag('pic.png') %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h4> Hole Size (H) </h4>
        <%= f.input :hole_size,  label: false,priority: [ "8" ], collection: [ "8", "10", "12"] %>
      </div>
      <div class="col-md-3">
        <h4> Pilot Diameter (P) </h4>
        <%= f.input :hole_size, label: false, priority: [ "50" ], collection: [ "50", "57"] %>
      </div>
    <div class="col-md-3">
      <h4> X = Y </h4>
      <%= f.input :pattern_type, label: false, priority: [ "square" ], collection: [ "square", "rectangle"] %>
    </div>
    <div class="col-md-3">
      <p> If X = Y, the pattern is a square</p>
      <p> If X doesn't equal Y, the pattern is a rectangle</p>
    </div>
  </div>



   <h2 class="text-center default-form"> Transmission Details
    </h2>
    <div class="row">
      <div class="col-md-3">
         <h4>Transmission Type </h4>
         <%= f.input :transmission_type, label: false, placeholder:"",  priority: [ "Camaro/Firebird" ], collection: [ "Camaro/Firebird", "GTO", "Truck", "Cadillac"] %>
       </div>
      <div class="col-md-3">
         <h4>Transmission Details </h4>
         <%= f.input :transmission_detail, label: false, placeholder:"",  priority: [ "Auto" ], collection: [ "Auto", "T56", "TR 6060", "Magnum", "Treme", "TKO", "Bolt on Yoke", "Slip Yoke"] %>
       </div>
     </div row>
    <p> These parts are for LS only - the ZCar small block Chevy kit is a different product. It is $695.00. No parts interchange with the LS. Please use the correct order sheet for the small block V8 conversion </p>

    <h2 class="text-center default-form"> LS Building Blocks Monies (FRT Paid)
     </h2>

     <table class="table table-bordered">
       <thead>
         <tr>
           <th class="col-md-4"> LS ZCar Front mount set</th>
           <th class="col-md-4"> </th>
           <th class="col-md-4"> $295.00 </th>
         </tr>
       </thead>
       <tbody>
         <tr>
           <td class="col-md-4">Trans Crossmemeber and mount </td>
           <td class="col-md-4">$135.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :trans_crossmember, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">Driveshaft- ready to install </td>
           <td class="col-md-4">$255.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :driveshaft, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">RH Monies <%= f.input :rh_monies, label: false, priority: [ "TR 6060" ], collection: [ "TR 6060", "Magnum", "Tremec", "TKO"] %> </td>
           <td class="col-md-4">Call for price </td>
           <td class="col-md-4"> <%= f.collection_radio_buttons :rh_monies_yes, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">Speedometer Drive Unit </td>
           <td class="col-md-4">$345.oo </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :speedometer, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">Vital Liquids set </td>
           <td class="col-md-4">$105.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :vital_liquids, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">Header Set (NOT California) </td>
           <td class="col-md-4">$385.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :header_set, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">AC Compressor & mounting kit </td>
           <td class="col-md-4">$450.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :ac_compressor_mount_kit, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">AC Hose Kit (factory AC '77-78) </td>
           <td class="col-md-4">$200.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :ac_hose_kit, [[true, 'Yes'], [false, 'No']], :first, :last %> </td>
         </tr>
         <tr>
           <td class="col-md-4">High Volume fuel pump </td>
           <td class="col-md-4">$175.00 </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :high_volume, [[true, 'Yes'], [false, 'No']], :first, :last%> </td>
         </tr>
         <tr>
           <td class="col-md-4">Are you a Texas Resident? </td>
           <td class="col-md-4"> Sales Tax -- 8.25% </td>
           <td class="col-md-4"><%= f.collection_radio_buttons :texas_resident, [[true, 'Yes'], [false, 'No']], :first, :last%> </td>
         </tr>
       </tbody>
     </table>

     <p> LS ZCar V8 Conversion components are property of John's Cars, Inc., including the design, parts and procedures; All Rights Reserved. Our Conversion parts are for the purchaser's personal use and not to be duplicated in whole or in part even if altered. Please check with local authorities regarding emission controls where required. John's Cars, Inc. assumes no liability regarding purchaser's installation or use. </p>

    <%= f.submit "Submit Order" %>

  <% end %>
</div>

app/views/order_sheets/show.html.erb
<br><br><br><br>
<div class="container">
  <p> Your LS ZCar form was generated correctly. <%= link_to "Click Here", print_order_sheet_pdf_path(@order_sheet.id, format: :pdf) %> to print your order form. </p>
  <br><br>
  <p> Need to Edit your LS ZCar order form? <%= link_to "Click Here", edit_order_sheet_path(@order_sheet.id) %> to edit your form. </p>
</div>